# Generated by Django 5.2.5 on 2025-08-09 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('watched', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('number_of_steps', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.trail'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('trail', 'position')},
        ),
    ]
