# Generated by Django 5.2.5 on 2025-08-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='number_of_steps',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
