# Generated by Django 5.2.5 on 2025-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0002_alter_trail_number_of_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='position',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
