# Generated by Django 5.2.5 on 2025-08-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0004_remove_link_create_at_link_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trail',
            name='autor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
